-- PostgreSQL schema for awesome_blog
-- Usage:
--   1) create database awesome_blog;
--   2) connect to awesome_blog;
--   3) run this script.

create table if not exists users (
    id varchar(50) primary key,
    email varchar(50) not null,
    password varchar(50) not null,
    admin boolean not null,
    name varchar(50) not null,
    image varchar(500) not null,
    created_at double precision not null,
    updated_at double precision not null
);

create unique index if not exists idx_users_email on users (email);
create index if not exists idx_users_created_at on users (created_at);

create table if not exists blogs (
    id varchar(50) primary key,
    user_id varchar(50) not null,
    user_name varchar(50) not null,
    user_image varchar(500) not null,
    name varchar(500) not null,
    description varchar(2048),
    summary varchar(2048) not null,
    content text not null,
    tags varchar(500),
    category_id varchar(50),
    category_name varchar(50),
    view_count integer not null default 0,
    created_at double precision not null,
    updated_at double precision not null,
    enabled boolean not null default true
);

create index if not exists idx_blogs_created_at on blogs (created_at);
create index if not exists idx_blogs_enabled_created_at on blogs (enabled, created_at);

create table if not exists comments (
    id varchar(50) primary key,
    blog_id varchar(50) not null,
    user_id varchar(50) not null,
    user_name varchar(50) not null,
    user_image varchar(500) not null,
    content text not null,
    created_at double precision not null
);

create index if not exists idx_comments_created_at on comments (created_at);
create index if not exists idx_comments_blog_id_created_at on comments (blog_id, created_at);

create table if not exists comments_anonymous (
    id varchar(50) primary key,
    parent_id varchar(50),
    blog_id varchar(50) not null,
    target_name varchar(255),
    content text not null,
    name varchar(50) not null,
    email varchar(50),
    website varchar(100),
    avatar varchar(200),
    ip varchar(50),
    created_at double precision not null
);

create index if not exists idx_comments_anonymous_created_at on comments_anonymous (created_at);
create index if not exists idx_comments_anonymous_blog_id_created_at on comments_anonymous (blog_id, created_at);

create table if not exists categories (
    id varchar(50) primary key,
    name varchar(50) not null,
    created_at double precision not null,
    updated_at double precision not null
);

create index if not exists idx_categories_created_at on categories (created_at);

create table if not exists tags (
    id integer generated by default as identity primary key,
    name varchar(50) not null,
    created_at double precision not null,
    updated_at double precision not null
);

create index if not exists idx_tags_created_at on tags (created_at);
